<a href="https://colab.research.google.com/github/manishrathod2003/Machine-Learning/blob/main/Day1_24feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Resource - https://automatetheboringstuff.com/

## NumPy

In [ ]:
import numpy as np

#Create NumPy Array

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [ ]:
arr = np.array([1,2,3,'abc',4,5])
print(arr)
print(type(arr))
print(arr.dtype)

['1' '2' '3' 'abc' '4' '5']
<class 'numpy.ndarray'>
<U21


In [ ]:
#Lists

#range(start,stop)
lst = list(range(1,10))
print(lst)

#range(start,stop,step)
lst = list(range(1,10,2))
print(lst)

#range(0,n-1)
lst = list(range(10))      # n=10
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#arange()

arr = np.arange(1,10)
print(arr)

arr = np.arange(1,10,2)
print(arr)

arr = np.arange(10)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(arr[0])

0


In [ ]:
#Create 2D Array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("No. of dimensions:",arr.ndim)
print("Shape(rows,columns):",arr.shape)
print("No. of elements:",arr.size)
print("Data Type:",arr.dtype)
print(arr[2][1])                   #row index, column index

[[1 2 3]
 [4 5 6]
 [7 8 9]]
No. of dimensions: 2
Shape(rows,columns): (3, 3)
No. of elements: 9
Data Type: int64
8


In [ ]:
arr1 = np.array([1,2,3])
print(arr1.ndim)

1


In [ ]:
arr2 = np.ones(5)
print(arr2)
print(arr2.dtype)


[1. 1. 1. 1. 1.]
float64


In [ ]:
arr=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])
print(arr)

for i in arr:
    print(i)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
[ 1  2  3 10]
[ 4  5  6 11]
[ 7  8  9 12]


In [ ]:
for i in np.nditer(arr):
    print(i)

1
2
3
10
4
5
6
11
7
8
9
12


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11],[20,21],[30,31]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[10 11]
 [20 21]
 [30 31]]


In [ ]:
arr3 = np.dot(arr1,arr2)
print(arr3)

[[140 146]
 [320 335]]


In [ ]:
#Shape Change operations
arr=np.array([1,2,3,4,5,6])
print(arr.ndim)

arr_new = arr.reshape(2,3)
print(arr_new)
print(arr_new.ndim)

arr_new = arr.reshape(3,2)
print(arr_new)
print(arr_new.ndim)

arr_new = arr.reshape(6,1)
print(arr_new)
print(arr_new.ndim)

1
[[1 2 3]
 [4 5 6]]
2
[[1 2]
 [3 4]
 [5 6]]
2
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Array:\n",arr)
print("Transpose of Array:\n",arr.T)
print("Transpose of Array:\n",np.transpose(arr))
print("Transpose of Array:\n",arr.transpose())

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Useful functions in numpy

sales = np.array([2345,6547,8965,8965,5690,2356])
print("Total Sales:",sales.sum())
print("Maximum Sales:",sales.max())
print("Minimum Sales:",sales.min())
#print(f"High:{sales.max()} Low:{sales.min()}")
print("Mean Sales:",sales.mean())
print("Standard Deviation:",sales.std())
print("Variance:",sales.var())

Total Sales: 34868
Maximum Sales: 8965
Minimum Sales: 2345
Mean Sales: 5811.333333333333
Standard Deviation: 2720.353816857081
Variance: 7400324.888888888


In [ ]:
#Broadcasting of Operations
lst=[10,20,30]                    #operations not performed on all elements in a list
print(lst*3)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [ ]:
arr = np.array([10,20,30])         #operations performed on all elements in a array
print(arr*3)

[30 60 90]


In [ ]:
#Membership Opeartions - in and not in
print(10 in arr)

print(10 not in arr)
print(12 not in arr)

True
False
True
